name: short_video_sharing_app
description: "Short Video Sharing Application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^1.2.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  flutter_lints: ^5.0.0
  universal_html: ^2.2.4
  image_picker_web: ^4.0.0

flutter:

  uses-material-design: true
